name: Generate Tar Archives
on:
  push:
    branches:
      - main
jobs:
  Create-Tar-Archives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: Archives
          path: "*.tar.xz"
